# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1d685829550c46fcec4569647a8d6abd5891d4f686d40e29eff76c24fed76482f7b4f5549e264f0677fab5f94671efb5b02b69444e1f93f2a11ed3156a25e66

test:
  secret_key_base: 856d862a9f4b54d1c5c18a19f6b43cfb120649de4e9f19f3fedabb5e30faa0a82f4878154c55da99c0a7174030d819b9ea3f0422ce908adc5b538670b2d82bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
